services:
  - type: web
    name: whatsapp-commerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn whatsapp_commerce.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-commerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A whatsapp_commerce worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-commerce-db
          property: connectionString

databases:
  - name: whatsapp-commerce-db
    plan: free
